// Shared bilingual copy + form helper for all GrowIndie Digital pages.
window.GI_T = {
  en: {
    navHome: "Home", navAbout: "About", navServices: "Services", navIndustries: "Industries", navPricing: "Pricing", navTestimonials: "Testimonials", navFaq: "FAQ", navContact: "Contact",
    navCta: "Get a Free Audit", skipLink: "Skip to main content",
    heroBadge: "Now onboarding brands across India",
    heroHeadline: "We build brands that outgrow their market.",
    heroSub: "GrowIndie Digital plans, builds, and runs the marketing systems ambitious Indian businesses use to win — SEO, Google and Meta ads, WhatsApp, brand, and web, engineered together instead of stitched from six vendors.",
    heroCtaPrimary: "Get a Free Marketing Audit", heroCtaSecondary: "See How We Work",
    heroCard1: "Turnaround on your free marketing audit", heroCard2: "Markup on your ad spend — Google and Meta bill your card direct", heroCard3: "Live dashboard access to spend, leads and cost per lead",
    quickGlanceLabel: "Quick glance", quickGlanceTitle: "Everything you'll find on this site",
    qg1Title: "About us", qg1Desc: "Why we work differently, and how our five-step process runs.",
    qg2Title: "Services", qg2Desc: "Marketing, branding, creative, and technology under one roof.",
    qg3Title: "Industries", qg3Desc: "Built for founders who move fast — in Tamil Nadu and beyond.",
    qg4Title: "Pricing", qg4Desc: "Published starting rates, no markup on ad spend, no surprises.",
    qg5Title: "Testimonials", qg5Desc: "Real reviews from South Tamil Nadu businesses we've grown.",
    qg6Title: "FAQ", qg6Desc: "Straight answers on timelines, pricing, and how we work.",
    footerConnect: "Talk to us", footerLegalLine: "GrowIndie Digital, Thoothukudi, Tamil Nadu 628001, India.",
    footerQuickLinks: "Quick links", footerServicesCol: "Services",
    servicesEyebrow: "What we do", servicesTitle: "We don't just market brands. We grow them.", servicesSub: "Branding, marketing, creative, and technology under one roof — no hand-offs between six vendors.",
    tabMarketing: "Marketing", tabBranding: "Branding", tabCreative: "Creative", tabTech: "Technology", tabSpecial: "Special Services",
    sMSeoTitle: "SEO", sMSeoDesc: "Ranking systems built on technical fundamentals, not link-farm shortcuts.",
    sMAdsTitle: "Google Ads (PPC)", sMAdsDesc: "Search, Shopping, and Performance Max accounts tuned for profit, not just clicks.",
    sMSmmTitle: "Social Media Marketing", sMSmmDesc: "Paid and organic social built to move people, not just impressions.",
    sMSmMgmtTitle: "Social Media Management", sMSmMgmtDesc: "Day-to-day publishing, community, and reporting handled end to end.",
    sMContentTitle: "Content Marketing", sMContentDesc: "Editorial calendars engineered to compound organic traffic, not just fill a blog.",
    sMCopyTitle: "Copywriting", sMCopyDesc: "Ads, pages, and emails written to convert — in English or Tamil.",
    sMEmailTitle: "Email Marketing", sMEmailDesc: "Lifecycle flows and campaigns that turn your list into a real revenue channel.",
    sMWhatsappTitle: "WhatsApp Marketing", sMWhatsappDesc: "Broadcast, catalogue, and automated follow-up on the channel India actually replies on.",
    sMInfluencerTitle: "Influencer Marketing", sMInfluencerDesc: "Creator partnerships sourced, briefed, and measured against real pipeline.",
    sMYoutubeTitle: "YouTube Channel Management", sMYoutubeDesc: "Packaging, publishing, and growth strategy for channels built to last.",
    sMMediaTitle: "Media Buying & Campaign Management", sMMediaDesc: "Budget planning and hands-on campaign management across every major platform.",
    sBLogoTitle: "Logo Design", sBLogoDesc: "Marks designed to read clearly at every size, from a signboard to a favicon.",
    sBIdentityTitle: "Brand Identity", sBIdentityDesc: "Colour, type, and asset systems your whole team can apply without us.",
    sBStrategyTitle: "Brand Strategy", sBStrategyDesc: "Positioning, voice, and messaging built to survive scale.",
    sCGraphicTitle: "Graphic Design", sCGraphicDesc: "Visual systems for ads, decks, and packaging that stay on-brand at any size.",
    sCPhotoTitle: "Photography & Videography", sCPhotoDesc: "Shoots planned around the campaign the footage has to feed.",
    sCProductTitle: "Product Advertisements", sCProductDesc: "Product-led ad creative built for scroll-stopping first frames.",
    sCShortsTitle: "Short-form Video Editing", sCShortsDesc: "Reels and Shorts cut for retention, not just polish.",
    sTWebTitle: "Website Design & Development", sTWebDesc: "Fast, conversion-first sites built on a real design system, not a page builder.",
    sTAnalyticsTitle: "Analytics & Performance Reporting", sTAnalyticsDesc: "Clean tracking and dashboards so every decision traces back to real numbers.",
    sTAiTitle: "AI-Powered Marketing Solutions", sTAiDesc: "AI-assisted creative, targeting, and reporting layered onto proven channels.",
    sTConsultTitle: "Marketing Consultation & Strategy", sTConsultDesc: "Fractional CMO-level guidance for teams building their first real growth engine.",
    sSPhotoTitle: "Wedding & Event Photography", sSPhotoDesc: "Full-day coverage with a considered edit, delivered on a schedule you can plan around.",
    sSVideoTitle: "Wedding & Event Videography", sSVideoDesc: "Films and highlight cuts shot with the same craft we bring to brand work.",
    aboutEyebrow: "About GrowIndie", aboutTitle: "Marketing run like a product, not a project.",
    whyEyebrow: "Why GrowIndie", whyTitle: "Marketing run like a product, not a project.",
    whySub: "Most agencies hand you a report. We hand you a system — instrumented, documented, and owned by a team that treats your growth targets as our own.",
    why1Title: "One team, full funnel", why1Desc: "Strategy, media, and creative sit in one room, so nothing gets lost in translation.",
    why2Title: "Built on data, not guesses", why2Desc: "Every recommendation is backed by clean tracking and a documented hypothesis.",
    why3Title: "Built for the Indian market", why3Desc: "From Chennai retail to pan-India D2C, campaigns are built for how people here actually search, scroll, and buy — in English or Tamil.",
    floatCard1Label: "MONTHLY REVENUE", floatCard2Label: "CAMPAIGN HEALTH", floatCard2Value: "All systems optimal",
    processEyebrow: "How we work", processTitle: "Five steps. No guesswork.",
    step1Title: "Discover", step1Desc: "Audit your market, funnel, and current spend.",
    step2Title: "Strategy", step2Desc: "Set channel mix, targets, and a 90-day roadmap.",
    step3Title: "Build & Launch", step3Desc: "Creative, pages, and campaigns go live.",
    step4Title: "Optimize", step4Desc: "Weekly testing against a shared scorecard.",
    step5Title: "Scale", step5Desc: "Double down on what's proven to compound.",
    trustEyebrow: "Full transparency",
    trustTitle: "Your ad accounts stay yours. Every rupee is visible.",
    trustSub: "Ad spend is billed by Google and Meta straight to your card — we never resell it with a markup. You keep admin access, we work inside your accounts, and if you ever leave, everything stays with you.",
    trust1Title: "You own the accounts", trust1Desc: "Google Ads, Meta Business, GA4, and Google Business Profile are created under your name with you as admin.",
    trust2Title: "Direct platform billing", trust2Desc: "Your card is on file with Google and Meta. You see the exact spend they charge — no agency invoice sitting in between.",
    trust3Title: "Live dashboard access", trust3Desc: "A shared Looker Studio dashboard pulling spend, leads, and cost per lead straight from the ad platforms, open to you 24/7.",
    trust4Title: "Reports you can audit", trust4Desc: "Monthly reviews in Tamil or English that reconcile against Ads Manager line by line — including what did not work.",
    trustPlatformsLabel: "We work inside", trustBadgesLabel: "Certifications",
    commitmentLabel: "Our commitment", commitment1: "No lock-in — 30 days' notice to leave", commitment2: "Your data and accounts stay yours", commitment3: "Direct WhatsApp line to your strategist",
    industriesEyebrow: "Who we work with", industriesTitle: "Built for founders who move fast — anywhere.",
    ind1: "Startups & SaaS", ind2: "Ecommerce & DTC", ind3: "Healthcare", ind4: "Real Estate", ind5: "Restaurants & Hospitality", ind6: "Manufacturing", ind7: "Personal Brands", ind8: "Local Services",
    testiEyebrow: "Client reviews", testiTitle: "What businesses across Tamil Nadu say.",
    testi1Quote: "“Aadi season used to mean printing 5,000 notices and hoping someone walked in. They ran Tamil ads to a 15 km radius instead — 240 WhatsApp enquiries in three weeks, and I could see exactly what each one cost me.”", testi1Initials: "KR", testi1Name: "Karthik R.", testi1Role: "Owner, textile showroom", testi1Loc: "Thoothukudi",
    testi2Quote: "“We ship halwa all over Tamil Nadu but our ads were still in English. They rewrote everything in Tamil, fixed the WhatsApp catalogue, and by month two our cost per order had come down from ₹410 to ₹190.”", testi2Initials: "MS", testi2Name: "Meena S.", testi2Role: "Owner, sweets & snacks brand", testi2Loc: "Tirunelveli",
    testi3Quote: "“Three branches, and the Google listing for two of them had the wrong timings for years. They fixed it and now most new patients tell us they called straight from Google. They also drive down for the shoots — no agency in Chennai was doing that for us.”", testi3Initials: "AP", testi3Name: "Dr. Arun P.", testi3Role: "Partner, dental clinic chain", testi3Loc: "Nagercoil",
    roiEyebrow: "Growth calculator", roiTitle: "See what your budget could return.", roiSub: "A directional estimate based on category benchmarks — your free audit gives you the real numbers.",
    roiSpendLabel: "Monthly ad spend", roiIndustryLabel: "Industry", roiEcommerce: "Ecommerce", roiSaas: "SaaS", roiLocal: "Local Services",
    roiLeadsLabel: "Estimated monthly leads", roiRoasLabel: "Projected ROAS range", roiDisclaimer: "Based on 2026 India cost-per-lead benchmarks (D2C ₹50–200, local services ₹200–500, B2B SaaS ₹800–2,000). Actual results vary by city, offer, and creative — spends under ₹15,000/month rarely exit the learning phase.",
    pricingEyebrow: "Investment", pricingTitle: "Pricing built around your goals, not a template.", pricingSub: "Every retainer is scoped to your goals after a free audit — no template packages, no surprise line items.",
    perMonth: "", tier1Price: "Tailored to you", tier2Price: "Tailored to you", tier3Price: "Tailored to you",
    pricingNote: "Retainer pricing is scoped to your goals after the audit. Ad spend is billed directly by Google and Meta, so you always see exactly what was spent. Six-month commitments earn 10–20% better rates.",
    tier1Name: "Launch", tier1Desc: "For local Thoothukudi businesses building their first real growth channel.", tier1F1: "1–2 core channels", tier1F2: "Monthly strategy calls", tier1F3: "Core tracking setup",
    tier2Name: "Ascend", tier2Desc: "For brands running ads, content, and creative together — our most common engagement.", tier2F1: "Full channel mix + creative", tier2F2: "Weekly optimization sprints", tier2F3: "Dedicated strategist",
    tier3Name: "Dominate", tier3Desc: "For multi-location or pan-India brands with complex channel needs.", tier3F1: "Multi-market strategy", tier3F2: "Dedicated pod + analyst", tier3F3: "Custom reporting & SLAs",
    tierCta: "Book a Free Audit", mostPopular: "Most popular",
    faqEyebrow: "FAQ", faqTitle: "Questions, answered.",
    faq1Q: "How fast will I see results?", faq1A: "Paid channels typically show early signal within 2–4 weeks; SEO and organic content compound over 3–6 months. Your audit gives a channel-specific timeline before you commit.",
    faq2Q: "Do you only work with businesses in Tamil Nadu?", faq2A: "No — we run campaigns across India, from Chennai and Coimbatore to Bengaluru, Hyderabad, Mumbai and Delhi NCR, plus NRI-facing brands in the UAE and Singapore. All of it in English or Tamil, on IST.",
    faq3Q: "What's included in the free marketing audit?", faq3A: "A review of your current channels, tracking setup, and competitive position, plus a prioritized list of where your budget would move the needle fastest — no obligation to sign anything.",
    faq4Q: "How is pricing structured?", faq4A: "Retainers are scoped to your goals after the audit. Ad spend is billed directly by Google and Meta so you see every rupee, no bloated retainers.",
    faq5Q: "Can you take over from our current agency or in-house team?", faq5A: "Yes — we regularly audit and take over accounts mid-flight, migrating tracking and ad accounts with zero downtime to live campaigns.",
    finalCtaTitle: "Ready to grow like it's your only option?", finalCtaSub: "Get a free, no-pressure audit of your current marketing — and a clear plan for what comes next.", finalCtaBtn: "Get My Free Audit",
    contactEyebrow: "Get started", contactTitle: "Request your free marketing audit.", contactSub: "Tell us about your business and we'll come back within one business day with a scoped plan — no cold-call sales pitch.",
    contactEmailLabel: "Email", contactPhoneLabel: "Phone / WhatsApp", contactSocialLabel: "Instagram", contactResponseLabel: "Response time", contactResponseValue: "Within 1 business day (IST)",
    formSuccessTitle: "Request received", formSuccessSub: "We'll be in touch within one business day.",
    formName: "Full name", formCompany: "Company", formEmail: "Work email", formWebsite: "Website", formBudget: "Monthly marketing budget",
    formBudget1: "Under ₹25,000", formBudget2: "₹25,000 – ₹1,00,000", formBudget3: "₹1,00,000 – ₹5,00,000", formBudget4: "₹5,00,000+",
    formGoals: "What are you looking to grow?", formSubmit: "Request My Free Audit",
    formSending: "Sending…", formError: "Something went wrong. Please WhatsApp us on +91 83447 35921 instead.",
    formPrivacy: "We use your details only to prepare and send your audit. No lists, no resale.",
    footerJoined: "Joined ✓",
    localEyebrow: "Thoothukudi & South Tamil Nadu",
    localTitle: "A local team that picks up the phone — and answers in Tamil.",
    localSub: "We are based in Thoothukudi, so campaign reviews, shoots, and store visits happen in person, not over a support ticket. Most agencies chasing Thoothukudi keywords are not actually here.",
    local1Title: "Tamil-first campaigns", local1Desc: "Ad copy, landing pages, and WhatsApp replies written in the Tamil your customers actually use — not translated English.",
    local2Title: "Shoots across South TN", local2Desc: "Product, store, and event shoots covered in person from Thoothukudi to Nagercoil, with the edit handled by the same team running your ads.",
    local3Title: "Ads and creative in one room", local3Desc: "You are not paying one agency for reels and another for performance. Strategy, creative, and media sit together, so campaigns ship in days.",
    localAreasLabel: "On the ground in", localRemoteLabel: "Working remotely with",
    localRemoteValue: "Chennai, Coimbatore, Bengaluru, Hyderabad, and NRI-facing brands in the UAE and Singapore — all on IST, in English or Tamil.",
    localWhatsapp: "WhatsApp us", localCall: "Call now",
    footerTagline: "Grow. Innovate. Dominate.", footerCompany: "Company", footerAbout: "About", footerCareers: "Careers", footerBlog: "Blog",
    footerLegal: "Legal", footerPrivacy: "Privacy Policy", footerTerms: "Terms of Service", footerNewsletter: "Stay in the loop", footerJoin: "Join",
    footerCopyright: "© 2026 GrowIndie Digital. All rights reserved."
  },
  ta: {
    navHome: "முகப்பு", navAbout: "எங்களைப் பற்றி", navServices: "சேவைகள்", navIndustries: "தொழில்துறைகள்", navPricing: "விலை", navTestimonials: "கருத்துகள்", navFaq: "கேள்விகள்", navContact: "தொடர்பு",
    navCta: "இலவச ஆடிட் பெறவும்", skipLink: "முதன்மை உள்ளடக்கத்திற்குச் செல்லவும்",
    heroBadge: "இந்தியா முழுவதும் புதிய பிராண்டுகளை இணைத்துக் கொள்கிறோம்",
    heroHeadline: "உங்கள் சந்தையை மிஞ்சும் பிராண்டுகளை நாங்கள் உருவாக்குகிறோம்.",
    heroSub: "SEO, Google மற்றும் Meta விளம்பரங்கள், WhatsApp, பிராண்டிங், வலைத்தளம் — இவற்றை தனித்தனி நிறுவனங்களிடம் ஒப்படைக்காமல், இந்திய வணிகங்கள் வெற்றிபெறத் தேவையான மார்க்கெட்டிங் அமைப்பை GrowIndie Digital ஒரே குழுவாக திட்டமிட்டு, உருவாக்கி, இயக்குகிறது.",
    heroCtaPrimary: "இலவச மார்க்கெட்டிங் ஆடிட் பெறவும்", heroCtaSecondary: "எங்கள் செயல்முறையைப் பாருங்கள்",
    heroCard1: "உங்கள் இலவச ஆடிட் திரும்பி வரும் நேரம்", heroCard2: "விளம்பர செலவில் எங்கள் மார்க்அப் — Google மற்றும் Meta உங்கள் கார்டில் நேரடியாக பில் செய்யும்", heroCard3: "செலவு, லீட்கள், லீட் விலை — நேரலை டாஷ்போர்டு அணுகல்",
    quickGlanceLabel: "சுருக்கமாக", quickGlanceTitle: "இந்த தளத்தில் நீங்கள் காணக்கூடியவை",
    qg1Title: "எங்களைப் பற்றி", qg1Desc: "நாங்கள் ஏன் வித்தியாசமாக செயல்படுகிறோம், எங்கள் ஐந்து-படி செயல்முறை.",
    qg2Title: "சேவைகள்", qg2Desc: "மார்க்கெட்டிங், பிராண்டிங், கிரியேட்டிவ், தொழில்நுட்பம் — ஒரே கூரையின் கீழ்.",
    qg3Title: "தொழில்துறைகள்", qg3Desc: "வேகமாக நகரும் நிறுவனர்களுக்காக — தமிழ்நாட்டிலும் அதற்கும் அப்பாலும்.",
    qg4Title: "விலை", qg4Desc: "வெளியிடப்பட்ட தொடக்க விலைகள், விளம்பர செலவில் மார்க்அப் இல்லை.",
    qg5Title: "கருத்துகள்", qg5Desc: "நாங்கள் வளர்த்த தென் தமிழ்நாடு வணிகங்களின் உண்மையான கருத்துகள்.",
    qg6Title: "கேள்விகள்", qg6Desc: "காலவரிசை, விலை, செயல்முறை பற்றிய நேரடி பதில்கள்.",
    footerConnect: "எங்களுடன் பேசுங்கள்", footerLegalLine: "GrowIndie Digital, தூத்துக்குடி, தமிழ்நாடு 628001, இந்தியா.",
    footerQuickLinks: "விரைவு இணைப்புகள்", footerServicesCol: "சேவைகள்",
    servicesEyebrow: "நாங்கள் செய்வது", servicesTitle: "நாங்கள் பிராண்டுகளை விளம்பரப்படுத்துவது மட்டுமல்ல — வளர்க்கிறோம்.", servicesSub: "பிராண்டிங், மார்க்கெட்டிங், கிரியேட்டிவ், தொழில்நுட்பம் — அனைத்தும் ஒரே கூரையின் கீழ்.",
    tabMarketing: "மார்க்கெட்டிங்", tabBranding: "பிராண்டிங்", tabCreative: "கிரியேட்டிவ்", tabTech: "தொழில்நுட்பம்", tabSpecial: "சிறப்பு சேவைகள்",
    sMSeoTitle: "SEO", sMSeoDesc: "தொழில்நுட்ப அடிப்படையில் கட்டமைக்கப்பட்ட ரேங்கிங் அமைப்புகள், குறுக்குவழிகள் இல்லை.",
    sMAdsTitle: "Google விளம்பரங்கள் (PPC)", sMAdsDesc: "Search, Shopping, Performance Max கணக்குகள் லாபத்திற்காக சீரமைக்கப்பட்டவை.",
    sMSmmTitle: "சமூக ஊடக மார்க்கெட்டிங்", sMSmmDesc: "வெறும் இம்ப்ரெஷன்கள் அல்ல — மக்களை நகர்த்தும் பெய்ட் மற்றும் ஆர்கானிக் சோஷியல்.",
    sMSmMgmtTitle: "சமூக ஊடக மேலாண்மை", sMSmMgmtDesc: "தினசரி பதிவுகள், சமூக உரையாடல், அறிக்கை — முழுவதும் நாங்கள் கவனிக்கிறோம்.",
    sMContentTitle: "உள்ளடக்க மார்க்கெட்டிங்", sMContentDesc: "ஆர்கானிக் ட்ராஃபிக்கை வளர்க்க வடிவமைக்கப்பட்ட எடிட்டோரியல் காலண்டர்கள்.",
    sMCopyTitle: "காப்பிரைட்டிங்", sMCopyDesc: "விளம்பரங்கள், பக்கங்கள், மின்னஞ்சல்கள் — ஆங்கிலத்திலும் தமிழிலும் மாற்றத்திற்காக எழுதப்படுகிறது.",
    sMEmailTitle: "மின்னஞ்சல் மார்க்கெட்டிங்", sMEmailDesc: "உங்கள் பட்டியலை உண்மையான வருவாய் வழியாக மாற்றும் ஃப்ளோக்கள்.",
    sMWhatsappTitle: "WhatsApp மார்க்கெட்டிங்", sMWhatsappDesc: "இந்தியா உண்மையில் பதிலளிக்கும் சேனலில் ப்ராட்காஸ்ட், கேட்டலாக், தானியங்கி பின்தொடர்வு.",
    sMInfluencerTitle: "இன்ஃப்ளூயன்சர் மார்க்கெட்டிங்", sMInfluencerDesc: "கிரியேட்டர் கூட்டாண்மைகள் — தேர்வு, பிரீஃப், உண்மையான முடிவுகளால் அளவிடல்.",
    sMYoutubeTitle: "YouTube சேனல் மேலாண்மை", sMYoutubeDesc: "நீண்டகாலம் வளரும் சேனல்களுக்கான பேக்கேஜிங், பதிவு, வளர்ச்சி மூலோபாயம்.",
    sMMediaTitle: "மீடியா பையிங் & பிரச்சார மேலாண்மை", sMMediaDesc: "எல்லா முக்கிய தளங்களிலும் பட்ஜெட் திட்டமிடல் மற்றும் நேரடி பிரச்சார மேலாண்மை.",
    sBLogoTitle: "லோகோ வடிவமைப்பு", sBLogoDesc: "சைன்போர்டு முதல் ஃபேவிகான் வரை எந்த அளவிலும் தெளிவாகத் தெரியும் அடையாளங்கள்.",
    sBIdentityTitle: "பிராண்ட் அடையாளம்", sBIdentityDesc: "உங்கள் குழுவே பயன்படுத்தக்கூடிய நிற, எழுத்துரு, அசெட் அமைப்புகள்.",
    sBStrategyTitle: "பிராண்ட் மூலோபாயம்", sBStrategyDesc: "அளவை தாங்கும் பொசிஷனிங், குரல், செய்தி அமைப்புகள்.",
    sCGraphicTitle: "கிராஃபிக் டிசைன்", sCGraphicDesc: "விளம்பரங்கள், டெக்குகள், பேக்கேஜிங்கிற்கான காட்சி அமைப்புகள்.",
    sCPhotoTitle: "புகைப்படம் & வீடியோகிராஃபி", sCPhotoDesc: "பிரச்சாரத்திற்குத் தேவையான காட்சிகளை மனதில் கொண்டு திட்டமிடப்பட்ட ஷூட்கள்.",
    sCProductTitle: "தயாரிப்பு விளம்பரங்கள்", sCProductDesc: "முதல் ஃப்ரேமிலேயே கவனத்தை நிறுத்தும் தயாரிப்பு விளம்பர கிரியேட்டிவ்.",
    sCShortsTitle: "ஷார்ட்-ஃபார்ம் வீடியோ எடிட்டிங்", sCShortsDesc: "தக்கவைப்புக்காக வெட்டப்பட்ட Reels மற்றும் Shorts.",
    sTWebTitle: "வலைத்தள வடிவமைப்பு & உருவாக்கம்", sTWebDesc: "உண்மையான டிசைன் அமைப்பில் கட்டமைக்கப்பட்ட வேகமான, மாற்ற-மையமான தளங்கள்.",
    sTAnalyticsTitle: "பகுப்பாய்வு & செயல்திறன் அறிக்கை", sTAnalyticsDesc: "ஒவ்வொரு முடிவும் உண்மையான எண்களை அடிப்படையாகக் கொள்ளும் டிராக்கிங் மற்றும் டாஷ்போர்டுகள்.",
    sTAiTitle: "AI சார்ந்த மார்க்கெட்டிங் தீர்வுகள்", sTAiDesc: "நிரூபிக்கப்பட்ட சேனல்களில் AI-உதவி கிரியேட்டிவ், டார்கெட்டிங், ரிப்போர்ட்டிங்.",
    sTConsultTitle: "மார்க்கெட்டிங் ஆலோசனை & மூலோபாயம்", sTConsultDesc: "முதல் உண்மையான வளர்ச்சி இயந்திரத்தை கட்டமைக்கும் குழுக்களுக்கான CMO-அளவிலான வழிகாட்டுதல்.",
    sSPhotoTitle: "திருமண & நிகழ்வு புகைப்படம்", sSPhotoDesc: "முழு நாள் கவரேஜ், கவனமான எடிட், நீங்கள் திட்டமிடக்கூடிய நேரத்தில் வழங்கல்.",
    sSVideoTitle: "திருமண & நிகழ்வு வீடியோகிராஃபி", sSVideoDesc: "பிராண்ட் வேலைக்கு நாங்கள் தரும் அதே கவனத்துடன் படமாக்கப்படும் ஃபிலிம்கள்.",
    aboutEyebrow: "GrowIndie பற்றி", aboutTitle: "மார்க்கெட்டிங் ஒரு தயாரிப்பு போல இயக்கப்படுகிறது, திட்டமாக அல்ல.",
    whyEyebrow: "ஏன் GrowIndie", whyTitle: "மார்க்கெட்டிங் ஒரு தயாரிப்பு போல இயக்கப்படுகிறது, திட்டமாக அல்ல.",
    whySub: "பெரும்பாலான நிறுவனங்கள் உங்களுக்கு ஒரு அறிக்கையை தருகின்றன. நாங்கள் உங்களுக்கு ஒரு அமைப்பை தருகிறோம் — கண்காணிக்கப்பட்டு, ஆவணப்படுத்தப்பட்டு, உங்கள் இலக்குகளை எங்கள் சொந்த இலக்குகளாகக் கருதும் குழுவால் நிர்வகிக்கப்படுகிறது.",
    why1Title: "ஒரே குழு, முழு ஃபன்னல்", why1Desc: "மூலோபாயம், மீடியா, கிரியேட்டிவ் அனைத்தும் ஒரே அறையில் — எதுவும் தொலைந்துபோகாது.",
    why2Title: "தரவின் அடிப்படையில், யூகங்களல்ல", why2Desc: "ஒவ்வொரு பரிந்துரையும் தூய டிராக்கிங் மற்றும் ஆவணப்படுத்தப்பட்ட கருதுகோளை அடிப்படையாகக் கொண்டது.",
    why3Title: "இந்திய சந்தைக்காக கட்டமைக்கப்பட்டது", why3Desc: "சென்னை சில்லறை வணிகம் முதல் இந்தியா முழுவதுமான D2C வரை — மக்கள் இங்கு எப்படி தேடுகிறார்கள், பார்க்கிறார்கள், வாங்குகிறார்கள் என்பதற்கு ஏற்ப பிரச்சாரங்கள். ஆங்கிலத்திலும் தமிழிலும்.",
    floatCard1Label: "மாத வருவாய்", floatCard2Label: "பிரச்சார நிலை", floatCard2Value: "அனைத்தும் சிறப்பாக செயல்படுகிறது",
    processEyebrow: "நாங்கள் எப்படி செயல்படுகிறோம்", processTitle: "ஐந்து படிகள். யூகங்கள் இல்லை.",
    step1Title: "கண்டறிதல்", step1Desc: "உங்கள் சந்தை, ஃபன்னல், தற்போதைய செலவை ஆய்வு செய்கிறோம்.",
    step2Title: "மூலோபாயம்", step2Desc: "சேனல் கலவை, இலக்குகள், 90-நாள் திட்டத்தை அமைக்கிறோம்.",
    step3Title: "உருவாக்கம் & வெளியீடு", step3Desc: "கிரியேட்டிவ், பக்கங்கள், பிரச்சாரங்கள் நேரலைக்கு வருகின்றன.",
    step4Title: "மேம்படுத்தல்", step4Desc: "பகிரப்பட்ட ஸ்கோர்கார்டுக்கு எதிராக வாராந்திர சோதனை.",
    step5Title: "விரிவாக்கம்", step5Desc: "நிரூபிக்கப்பட்டவற்றில் இரட்டிப்பு முதலீடு.",
    trustEyebrow: "முழு வெளிப்படைத்தன்மை",
    trustTitle: "உங்கள் விளம்பர கணக்குகள் உங்களுடையவை. ஒவ்வொரு ரூபாயும் தெரியும்.",
    trustSub: "விளம்பர செலவை Google மற்றும் Meta நேரடியாக உங்கள் கார்டில் பில் செய்யும் — நாங்கள் அதை லாபம் சேர்த்து மறுவிற்பனை செய்வதில்லை. அட்மின் அணுகல் உங்களிடமே; நீங்கள் விலகினாலும் அனைத்தும் உங்களுடன் இருக்கும்.",
    trust1Title: "கணக்குகள் உங்கள் பெயரில்", trust1Desc: "Google Ads, Meta Business, GA4, Google Business Profile அனைத்தும் உங்கள் பெயரில், நீங்களே அட்மின்.",
    trust2Title: "நேரடி பில்லிங்", trust2Desc: "உங்கள் கார்டு Google மற்றும் Meta-வில் பதிவு. அவர்கள் வசூலிக்கும் சரியான தொகை உங்களுக்குத் தெரியும் — இடையில் எங்கள் இன்வாய்ஸ் இல்லை.",
    trust3Title: "நேரலை டாஷ்போர்டு", trust3Desc: "செலவு, லீட்கள், லீட் விலை ஆகியவற்றை விளம்பர தளங்களிலிருந்து நேரடியாக காட்டும் Looker Studio டாஷ்போர்டு, 24/7 உங்களுக்கு திறந்திருக்கும்.",
    trust4Title: "சரிபார்க்கக்கூடிய அறிக்கைகள்", trust4Desc: "தமிழ் அல்லது ஆங்கிலத்தில் மாதாந்திர ஆய்வு — Ads Manager-உடன் வரிசைக்கு வரிசை பொருந்தும், வேலை செய்யாதவையும் சேர்த்து.",
    trustPlatformsLabel: "நாங்கள் பணிபுரியும் தளங்கள்", trustBadgesLabel: "சான்றிதழ்கள்",
    commitmentLabel: "ຎங்கள் ோருத்துரவு", commitment1: "லாக்-இன் இல்லை — 30 நாள் முன்றறிவிப்பில் விலகலாம்", commitment2: "உங்கள் தரவு மற்றும் கண்க்குகள் உங்கள்க்கே", commitment3: "உங்கள் மூலோபாயவாதிக்கு நேரடி WhatsApp இணைப்பு",
    industriesEyebrow: "நாங்கள் யாருடன் இணைந்து பணிபுரிகிறோம்", industriesTitle: "வேகமாக நகரும் நிறுவனர்களுக்காக — எங்கும்.",
    ind1: "தொடக்க நிறுவனங்கள் & SaaS", ind2: "ஈகாமர்ஸ் & DTC", ind3: "சுகாதாரம்", ind4: "ரியல் எஸ்டேட்", ind5: "உணவகங்கள் & விருந்தோம்பல்", ind6: "உற்பத்தி", ind7: "தனிநபர் பிராண்டுகள்", ind8: "உள்ளூர் சேவைகள்",
    testiEyebrow: "வாடிக்கையாளர் கருத்துகள்", testiTitle: "தமிழ்நாட்டு வணிகங்கள் சொல்வது.",
    testi1Quote: "“ஆடி சீசன் என்றால் 5,000 நோட்டீஸ் அடித்து யாராவது வருவார்களா என்று காத்திருப்பதுதான் வழக்கம். இவர்கள் 15 கி.மீ. சுற்றளவில் தமிழ் விளம்பரங்களை ஓட்டினார்கள் — மூன்று வாரங்களில் 240 WhatsApp விசாரணைகள், ஒவ்வொன்றுக்கும் எவ்வளவு செலவானது என்பதும் தெளிவாகத் தெரிந்தது.”", testi1Initials: "KR", testi1Name: "கார்த்திக் ர.", testi1Role: "உரிமையாளர், துணிக்கடை", testi1Loc: "தூத்துக்குடி",
    testi2Quote: "“தமிழ்நாடு முழுவதும் அல்வா அனுப்புகிறோம், ஆனால் விளம்பரங்கள் ஆங்கிலத்தில் இருந்தன. எல்லாவற்றையும் தமிழில் மாற்றி, WhatsApp கேட்டலாக்கையும் சரிசெய்தார்கள் — இரண்டாவது மாதத்திலேயே ஆர்டர் ஒன்றுக்கான செலவு ₹410-ல் இருந்து ₹190-க்கு வந்தது.”", testi2Initials: "MS", testi2Name: "மீனா ச.", testi2Role: "உரிமையாளர், இனிப்பு & தின்பண்ட நிறுவனம்", testi2Loc: "திருநெல்வேலி",
    testi3Quote: "“மூன்று கிளைகள், அதில் இரண்டின் Google பட்டியலில் நேரம் பல வருடங்களாகத் தவறாக இருந்தது. அதைச் சரிசெய்தார்கள்; இப்போது புதிய நோயாளிகள் பெரும்பாலும் Google-லிருந்து நேரடியாக அழைத்ததாகச் சொல்கிறார்கள். ஷூட்டுக்கும் இவர்களே வந்துவிடுகிறார்கள் — சென்னை நிறுவனங்கள் எதுவும் அதைச் செய்யவில்லை.”", testi3Initials: "AP", testi3Name: "டாக்டர் அருண் ப.", testi3Role: "பார்ட்னர், பல் மருத்துவமனை குழுமம்", testi3Loc: "நாகர்கோவில்",
    roiEyebrow: "வளர்ச்சி கால்குலேட்டர்", roiTitle: "உங்கள் பட்ஜெட் என்ன தரக்கூடும் எனப் பாருங்கள்.", roiSub: "பிரிவு அளவுகோல்களின் அடிப்படையில் ஒரு தோராயமான மதிப்பீடு — உங்கள் இலவச ஆடிட் உண்மையான எண்களை தரும்.",
    roiSpendLabel: "மாத விளம்பர செலவு", roiIndustryLabel: "தொழில்துறை", roiEcommerce: "ஈகாமர்ஸ்", roiSaas: "SaaS", roiLocal: "உள்ளூர் சேவைகள்",
    roiLeadsLabel: "மதிப்பிடப்பட்ட மாத லீட்கள்", roiRoasLabel: "எதிர்பார்க்கப்படும் ROAS வரம்பு", roiDisclaimer: "இது ஒரு தோராயமான மதிப்பீடு. உண்மையான முடிவுகள் சந்தை, சலுகை, செயல்படுத்தலைப் பொறுத்து மாறுபடும்.",
    pricingEyebrow: "முதலீடு", pricingTitle: "உங்கள் இலக்குகளுக்கு ஏற்ப கட்டமைக்கப்பட்ட விலை, டெம்ப்ளேட் அல்ல.", pricingSub: "ஒவ்வொரு ரீடெயினரும் உங்கள் இலவச ஆடிட்டுக்குப் பிறகு உங்கள் இலக்குகளுக்கு ஏற்ப வடிவமைக்கப்படும் — டெம்ப்ளேட் பேக்கேஜ்கள் இல்லை, எதிர்பாராத கட்டணங்கள் இல்லை.",
    perMonth: "", tier1Price: "உங்களுக்கேற்ப வடிவமைப்பு", tier2Price: "உங்களுக்கேற்ப வடிவமைப்பு", tier3Price: "உங்களுக்கேற்ப வடிவமைப்பு",
    pricingNote: "ரீடெயினர் விலை ஆடிட்டுக்குப் பிறகு உங்கள் இலக்குகளுக்கு ஏற்ப வடிவமைக்கப்படும். விளம்பர செலவு Google மற்றும் Meta-வால் நேரடியாக பில் செய்யப்படும், எனவே ஒவ்வொரு ரூபாயும் உங்களுக்குத் தெரியும். ஆறு மாத ஒப்பந்தங்களுக்கு 10–20% சிறந்த விலை.",
    tier1Name: "லான்ச்", tier1Desc: "தங்கள் முதல் உண்மையான வளர்ச்சி சேனலை உருவாக்கும் தொடக்க & உள்ளூர் பிராண்டுகளுக்கு.", tier1F1: "1–2 முக்கிய சேனல்கள்", tier1F2: "மாதாந்திர மூலோபாய அழைப்புகள்", tier1F3: "அடிப்படை டிராக்கிங் அமைப்பு",
    tier2Name: "ஏற்றம்", tier2Desc: "பெரிய அளவில் முழு-ஃபன்னல் வாங்குதலை இயக்கத் தயாராக உள்ள குழுக்களுக்கு.", tier2F1: "முழு சேனல் கலவை + கிரியேட்டிவ்", tier2F2: "வாராந்திர மேம்பாட்டு ஸ்பிரிண்ட்கள்", tier2F3: "பிரத்யேக மூலோபாயவாதி",
    tier3Name: "ஆதிக்கியத்துவம்", tier3Desc: "பல-சந்தை அல்லது பல-இட பிராண்டுகளுக்கான சிக்கலான தேவைகளுக்கு.", tier3F1: "பல-சந்தை மூலோபாயம்", tier3F2: "பிரத்யேக குழு + ஆய்வாளர்", tier3F3: "தனிப்பயன் ரிப்போர்ட்டிங் & SLA",
    tierCta: "இலவச ஆடிட் பெறவும்", mostPopular: "மிகவும் பிரபலமானது",
    faqEyebrow: "கேள்விகள்", faqTitle: "கேள்விகளுக்கான பதில்கள்.",
    faq1Q: "எவ்வளவு விரைவில் முடிவுகளை காண்பேன்?", faq1A: "பெய்ட் சேனல்கள் பொதுவாக 2–4 வாரங்களில் ஆரம்ப சமிக்ஞையை காட்டும்; SEO, ஆர்கானிக் உள்ளடக்கம் 3–6 மாதங்களில் கூடும். உங்கள் ஆடிட் நீங்கள் உறுதிசெய்யும் முன் ஒரு சேனல்-குறிப்பிட்ட காலவரிசையை தரும்.",
    faq2Q: "நீங்கள் தமிழ்நாட்டில் மட்டும் பணிபுரிகிறீர்களா?", faq2A: "இல்லை — சென்னை, கோயம்புத்தூர் முதல் பெங்களூரு, ஹைதராபாத், மும்பை, டெல்லி NCR வரை இந்தியா முழுவதும், மேலும் UAE மற்றும் சிங்கப்பூரில் உள்ள NRI சார்ந்த பிராண்டுகளுக்கும் பிரச்சாரங்களை இயக்குகிறோம். அனைத்தும் ஆங்கிலம் அல்லது தமிழில், IST நேரப்படி.",
    faq3Q: "இலவச மார்க்கெட்டிங் ஆடிட்டில் என்ன அடங்கும்?", faq3A: "உங்கள் தற்போதைய சேனல்கள், டிராக்கிங் அமைப்பு, போட்டி நிலை ஆகியவற்றின் மதிப்பாய்வு, மேலும் உங்கள் பட்ஜெட் வேகமாக பலனளிக்கும் இடங்களின் முன்னுரிமை பட்டியல் — எதையும் கையொப்பமிட வேண்டிய கட்டாயம் இல்லை.",
    faq4Q: "விலை எப்படி கட்டமைக்கப்படுகிறது?", faq4A: "ஆடிட்டுக்குப் பிறகு ஒவ்வொரு ஈடுபாடும் உங்கள் இலக்குகள் மற்றும் சேனல் கலவைக்கு ஏற்ப வடிவமைக்கப்படுகிறது, எனவே உண்மையில் உங்கள் எண்களை நகர்த்துவதற்கு மட்டுமே நீங்கள் செலுத்துகிறீர்கள். வெளியிடப்பட்ட விலை பட்டியல் இல்லை, பெரிய ரிடெய்னர்கள் இல்லை.",
    faq5Q: "எங்கள் தற்போதைய நிறுவனம் அல்லது இன்-ஹவுஸ் குழுவிடமிருந்து பொறுப்பேற்க முடியுமா?", faq5A: "ஆம் — நாங்கள் தொடர்ந்து இடையிலேயே கணக்குகளை ஆடிட் செய்து பொறுப்பேற்கிறோம், நேரலை பிரச்சாரங்களுக்கு எந்த இடையூறும் இல்லாமல் டிராக்கிங் மற்றும் விளம்பர கணக்குகளை மாற்றுகிறோம்.",
    finalCtaTitle: "உங்கள் ஒரே வழி வளர்ச்சி என்பது போல தயாரா?", finalCtaSub: "உங்கள் தற்போதைய மார்க்கெட்டிங்கின் இலவச, அழுத்தமில்லாத ஆடிட்டையும், அடுத்து என்ன செய்வது என்பதற்கான தெளிவான திட்டத்தையும் பெறுங்கள்.", finalCtaBtn: "எனது இலவச ஆடிட்டைப் பெறவும்",
    contactEyebrow: "தொடங்குங்கள்", contactTitle: "உங்கள் இலவச மார்க்கெட்டிங் ஆடிட்டைக் கோருங்கள்.", contactSub: "உங்கள் வணிகத்தைப் பற்றி எங்களிடம் கூறுங்கள், ஒரு வணிக நாளுக்குள் ஒரு வடிவமைக்கப்பட்ட திட்டத்துடன் திரும்பி வருவோம் — கோல்ட்-கால் விற்பனை பேச்சு இல்லை.",
    contactEmailLabel: "மின்னஞ்சல்", contactPhoneLabel: "தொலைபேசி / WhatsApp", contactSocialLabel: "Instagram", contactResponseLabel: "பதில் நேரம்", contactResponseValue: "1 வணிக நாளுக்குள் (IST)",
    formSuccessTitle: "கோரிக்கை பெறப்பட்டது", formSuccessSub: "ஒரு வணிக நாளுக்குள் உங்களைத் தொடர்புகொள்வோம்.",
    formName: "முழுப் பெயர்", formCompany: "நிறுவனம்", formEmail: "பணி மின்னஞ்சல்", formWebsite: "இணையதளம்", formBudget: "மாத மார்க்கெட்டிங் பட்ஜெட்",
    formBudget1: "₹25,000க்கு கீழ்", formBudget2: "₹25,000 – ₹1,00,000", formBudget3: "₹1,00,000 – ₹5,00,000", formBudget4: "₹5,00,000+",
    formGoals: "நீங்கள் என்ன வளர்க்க விரும்புகிறீர்கள்?", formSubmit: "எனது இலவச ஆடிட்டைக் கோரவும்",
    formSending: "அனுப்பப்படுகிறது…", formError: "ஏதோ தவறு நடந்தது. +91 83447 35921 இல் WhatsApp செய்யுங்கள்.",
    formPrivacy: "உங்கள் ஆடிட்டைத் தயாரித்து அனுப்புவதற்கு மட்டுமே உங்கள் விவரங்களைப் பயன்படுத்துகிறோம். பட்டியல்கள் இல்லை, மறுவிற்பனை இல்லை.",
    footerJoined: "சேர்ந்தது ✓",
    localEyebrow: "தூத்துக்குடி & தென் தமிழ்நாடு",
    localTitle: "தமிழில் பதிலளிக்கும் உள்ளூர் குழு.",
    localSub: "நாங்கள் தூத்துக்குடியில் இருக்கிறோம் — பிரச்சார ஆய்வுகள், ஷூட்கள், கடை வருகைகள் அனைத்தும் நேரில். தூத்துக்குடி கீவேர்டுகளைத் துரத்தும் பல நிறுவனங்கள் உண்மையில் இங்கு இல்லை.",
    local1Title: "தமிழ் முதன்மையான பிரச்சாரங்கள்", local1Desc: "உங்கள் வாடிக்கையாளர்கள் பயன்படுத்தும் தமிழில் விளம்பர வாசகங்கள், பக்கங்கள், WhatsApp பதில்கள் — மொழிபெயர்ப்பு அல்ல.",
    local2Title: "தென் தமிழ்நாடு முழுவதும் ஷூட்கள்", local2Desc: "தூத்துக்குடி முதல் நாகர்கோவில் வரை தயாரிப்பு, கடை, நிகழ்வு ஷூட்கள் நேரில் — எடிட்டும் உங்கள் விளம்பரங்களை இயக்கும் அதே குழுவால்.",
    local3Title: "விளம்பரமும் கிரியேட்டிவும் ஒரே இடத்தில்", local3Desc: "ரீல்களுக்கு ஒரு நிறுவனம், விளம்பரங்களுக்கு இன்னொன்று வேண்டாம். மூலோபாயம், கிரியேட்டிவ், மீடியா ஒன்றாக — பிரச்சாரங்கள் நாட்களில் தொடங்கும்.",
    localAreasLabel: "நேரடி சேவை", localRemoteLabel: "தொலைவிலிருந்து பணி",
    localRemoteValue: "சென்னை, கோயம்புத்தூர், பெங்களூரு, ஹைதராபாத், மேலும் UAE மற்றும் சிங்கப்பூரில் உள்ள NRI பிராண்டுகள் — அனைத்தும் IST நேரப்படி, ஆங்கிலம் அல்லது தமிழில்.",
    localWhatsapp: "WhatsApp செய்யுங்கள்", localCall: "இப்போது அழைக்கவும்",
    footerTagline: "Grow. Innovate. Dominate.", footerCompany: "நிறுவனம்", footerAbout: "எங்களைப் பற்றி", footerCareers: "வேலைவாய்ப்புகள்", footerBlog: "வலைப்பதிவு",
    footerLegal: "சட்டப்பூர்வ", footerPrivacy: "தனியுரிமைக் கொள்கை", footerTerms: "விதிமுறைகள்", footerNewsletter: "இணைந்திருங்கள்", footerJoin: "சேரவும்",
    footerCopyright: "© 2026 GrowIndie Digital. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை."
  }
};

window.GI_FORM = {
  ENDPOINT: 'https://api.web3forms.com/submit',
  KEY: '973c84a7-c542-4740-9e2e-35b76fc51891',
  async postForm(form, subject) {
    const fd = new FormData(form);
    if (fd.get('botcheck')) return;
    fd.append('access_key', this.KEY);
    fd.append('subject', subject);
    fd.append('from_name', 'GrowIndie Digital website');
    const res = await fetch(this.ENDPOINT, { method: 'POST', body: fd, headers: { Accept: 'application/json' } });
    const json = await res.json().catch(() => null);
    if (!res.ok || !json || json.success !== true) throw new Error('Submit failed');
  }
};
